[general]
import = ["~/.config/alacritty/colors.toml"]
live_config_reload = true

[window]
padding = {x = 20, y = 20}
dynamic_padding = true

[font]
size = 15
normal = {family = "monospace"}

[cursor]
style = {shape = "Block", blinking = "Off"}
unfocused_hollow = false
